services:
  backend:
    container_name: forum-backend 
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - PORT=${PORT:-80}
    ports:
      - "${PORT:-80}:${PORT:-80}"
    depends_on:
      cache:
        condition: service_healthy
  cache:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 10s
      timeout: 5s
      retries: 5
