"""add order column to Forum table

Revision ID: 8cb1cfde1fb8
Revises: d5f18fe43d8f
Create Date: 2026-02-17 01:52:38.444371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cb1cfde1fb8'
down_revision: Union[str, Sequence[str], None] = 'd5f18fe43d8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forums', sa.Column('order', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'forums', ['order'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'forums', type_='unique')
    op.drop_column('forums', 'order')
    # ### end Alembic commands ###
