"""remove Module and Action tables

Revision ID: 3324c85ad4ed
Revises: ca880a2b175c
Create Date: 2026-02-15 00:52:40.882477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3324c85ad4ed'
down_revision: Union[str, Sequence[str], None] = 'ca880a2b175c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role_permissions')
    op.drop_table('actions')
    op.drop_table('modules')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modules',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('modules_pkey')),
    sa.UniqueConstraint('name', name=op.f('modules_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('actions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('actions_pkey')),
    sa.UniqueConstraint('name', name=op.f('actions_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('module_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], name=op.f('role_permissions_action_id_fkey')),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], name=op.f('role_permissions_module_id_fkey')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('role_permissions_role_id_fkey')),
    sa.PrimaryKeyConstraint('role_id', 'module_id', 'action_id', name=op.f('role_permissions_pkey'))
    )
    # ### end Alembic commands ###
