name: Deploy Frontend

on:
  push:
    branches: [ "main" ]
    paths:
      - 'frontend/**'
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@main
        with:
          role-to-assume: ${{ secrets.AWS_FRONTEND_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Install node
        uses: actions/setup-node@v6
        with:
          node-version: 25

      - name: Build Frontend
        env:
          VITE_API_BASE_URL: ${{ vars.API_BASE_URL }}
        run: |
          npm ci
          npm run build

      - name: AWS S3 Sync
        run: |
          aws s3 sync dist s3://${{ vars.AWS_S3BUCKET_NAME }}
